  const authors = ['alexei kitaev',
    'austin fowler',
    'craig gidney',
    "Yuval Boger",
    'john martinis',
    'john preskill',
    "Hartmut Neven", 
    "Madelyn Cain", 
    "Jay M. Gambetta",
    "Mark Saffman",
    'Google quantum',];

  const keywords = [
    "asic",
    "benchmark",
    "bicycle code",
    "calibrate",
    "calibration",
    "characterization",
    "characterize",
    "circuit quantum electrodynamics",
    "circuit",
    "clifford",
    "coherent error",
    "correlated error",
    "cqed",
    "decode",
    "fpga",
    "gross code",
    "magic state",
    "markovian",
    "neutral atom",
    "noise",
    "noisy",
    "pauli",
    "photonic interconnect",
    "photonic qubit",
    "qec Codes",
    "qldpc",
    "quantum comput",
    "quantum error correction",
    "quantum software",
    "qubit",
    "simulator",
    "superconducting resonator",
    "surface code",
    "syndrome measurement",
    "toffoli",];
