  const authors = ['alexei kitaev',
    'sergio boixo',
    'austin fowler',
    'craig gidney',
    "Yuval Boger",
    'john martinis',
    'john preskill',
    "Hartmut Neven", 
    "Madelyn Cain", 
    "Jay M. Gambetta",
    "Mark Saffman",
    'Google quantum',];

  const keywords = [
"asic",
"benchmark",
"bicycle code",
"calibrate",
"calibration",
"characterization",
"characterize",
"circuit quantum electrodynamics",
"circuit",
"clifford",
"coherent error",
"correlated error",
"cqed",
"decode",
"decoding",
"error correct",
"fpga",
"ftqc",
"gidney",
"gross code",
"logical qubit",
"magic state",
"markovian",
"neutral atom",
"noise",
"noisy",
"oratomic",
"pauli",
"photonic interconnect",
"photonic qubit",
"preskill",
"psiquantum",
"qec Codes",
"qldpc",
"quantum archit",
"quantum comput",
"quantum error correction",
"quantum error",
"quantum software",
"quantum",
"qubit",
"quera",
"simulator",
"software",
"superconducting resonator",
"surface code",
"syndrome measurement",
"toffoli",
    ];
