  const authors = [
    'alexei kitaev',
    'austin fowler',
    'craig gidney',
    'google quantum',
    'hartmut neven',
    'jay m. gambetta',
    'john martinis',
    'john preskill',
    'madelyn cain',
    'mark saffman',
    'sergio boixo',
    'yuval boger',
];

  const keywords = [
"asic",
"benchmark",
"bicycle code",
"calibrate",
"calibration",
"characterization",
"characterize",
"circuit quantum electrodynamics",
"circuit",
"clifford",
"coherent error",
"correlated error",
"cqed",
"decode",
"decoding",
"error correct",
"fpga",
"ftqc",
"gidney",
"gross code",
"logical qubit",
"magic state",
"markovian",
"neutral atom",
"noise",
"noisy",
"oratomic",
"pauli",
"photonic interconnect",
"photonic qubit",
"preskill",
"psiquantum",
"qec Codes",
"qldpc",
"quantum archit",
"quantum comput",
"quantum error correction",
"quantum error",
"quantum software",
"quantum",
"qubit",
"quera",
"simulator",
"software",
"superconducting resonator",
"surface code",
"syndrome measurement",
"toffoli",
    ];
